### ISSUE TITLE
小爱触屏音箱（LX04）似乎不支持tts

### ISSUE THREAD

**Issue by SevenPlusJun** [smarthomefans/smarthomefans-nodes#12]
用非触屏和触屏 post，ubus 返回都是成功，但info中不返回mp3，不知有何解决办法？

触屏返回的信息
{
    "code": 0,
    "message": "Success",
    "data": {
        "code": 0,
        "info": "{\"is_mic_mute\":0}"
    }
}

**Comment by yaming116** [comment]
小爱不支持
